version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
    expose:
      - 4444
    networks:
        vpcbr:
          ipv4_address: 10.5.0.5
  
  
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/rhb4DedneuW/4C6lOeKLnkiFO31wQ0+uSuMJwJyCoVsBYS9WNdGwpJRzAFqh0HIKrbOvHl8eD0g2kWD/5DYPFrcGpke0hN9fpw4sxRn9T8bsE8AQSfXpqTPNKJlHyfMnZzuSRxrKNTUpPo8Veo+vgSMNonl25Vx2WhjSiKnc004K48RZtPP9XFT/mXCc+DWSaprnGidhcUXlO+ZajzvlrbXeIP1qlMPM55nDriS25ZemQwxJvXtRHJNiUyFgGKLKtHIQZOyowPXsEoppVGbsJ58jW13acrYP2/jvty/EZ8AddtGMBoIpiMsfM7xuIpPpBwiYAjU6mpAF5w5+iRKO4ZzsPbK2/vKYi2LSbJK2bt8f0U+fQAaZDVoby2Zwd1QItmy0MD8r6JH9J/ndDRhGjjuy8aOdir4K4W14D7Ch4BRNzjkOMedT2udxhkRQW5RQyIYQKL/BnAbdS9KyPwExok+dzwX9JZyJZ2zIi2PBbZocNTw8vUPpuPijoKkFcDc= eu\kulaarad@WCDV4733
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  
  agentubuntu:
    image: gccagent:latest
    privileged: true
    user: root
    container_name: agent-ubuntu
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/rhb4DedneuW/4C6lOeKLnkiFO31wQ0+uSuMJwJyCoVsBYS9WNdGwpJRzAFqh0HIKrbOvHl8eD0g2kWD/5DYPFrcGpke0hN9fpw4sxRn9T8bsE8AQSfXpqTPNKJlHyfMnZzuSRxrKNTUpPo8Veo+vgSMNonl25Vx2WhjSiKnc004K48RZtPP9XFT/mXCc+DWSaprnGidhcUXlO+ZajzvlrbXeIP1qlMPM55nDriS25ZemQwxJvXtRHJNiUyFgGKLKtHIQZOyowPXsEoppVGbsJ58jW13acrYP2/jvty/EZ8AddtGMBoIpiMsfM7xuIpPpBwiYAjU6mpAF5w5+iRKO4ZzsPbK2/vKYi2LSbJK2bt8f0U+fQAaZDVoby2Zwd1QItmy0MD8r6JH9J/ndDRhGjjuy8aOdir4K4W14D7Ch4BRNzjkOMedT2udxhkRQW5RQyIYQKL/BnAbdS9KyPwExok+dzwX9JZyJZ2zIi2PBbZocNTw8vUPpuPijoKkFcDc= eu\kulaarad@WCDV4733
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
