version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
    expose:
      - 4444
    networks:
        vpcbr:
          ipv4_address: 10.5.0.5

  agentubuntu:
    image: gccagent:latest
    privileged: true
    user: root
    container_name: agent-ubuntu
    expose:
      - 22
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
